### ISSUE TITLE
Add a rsync option.

### ISSUE THREAD

**Issue by thymon13** [ich777/docker-luckybackup#1]
Hello,

How to add "-z" rsync option to compress ?

thx in advance.

**Comment by ich777** [comment]
Select the sync, click `Modify`, click `Advanced`, click `Command Options`, click `User Defined`, enter `-z`, click `Add`, click `OK`

I will close this issue for now, please feel free to open the issue again if it's not solved for you.

**Comment by thymon13** [comment]
"click User Defined" 

Found ! LOL
It was really not readable in the interface...

**Comment by ich777** [comment]
> It was really not readable in the interface...

Open the VNC menu on the left side with the little arrow, click on the gear icon and at scaling select Server
